title: "Pitagoras 77"
author: "Miguel Montero"
description: "Website:<b style=\"color: #f45;\">&lt;IT Networks</b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "Home", icon: Home}
  - {title: "Search", url: "https://google.com", icon: Search}
  - {file: "README.md"}
  - {file: "04 The IOS Operating System Lab Exercises.pdf", title: LAB}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:miguelmonteroit@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/pitagoras77/pitagoras77.github.io"}
  - {title: twitter, icon: twitter, url: "https://twitter.com"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
